# alembic/script.py.mako
"""add_listing_extended_fields

Revision ID: fb9e689a7031
Revises: 
Create Date: 2025-12-21 18:31:14.692265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb9e689a7031'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'chat_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('channels', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_channels_active'), table_name='channels', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_channels_telegram_id'), table_name='channels')
    op.alter_column('deletion_log', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_deletion_log_detected'), table_name='deletion_log')
    op.alter_column('districts', 'city',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               nullable=False)
    op.alter_column('duplicates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_constraint(op.f('duplicates_original_id_duplicate_id_key'), 'duplicates', type_='unique')
    op.drop_index(op.f('idx_duplicates_duplicate'), table_name='duplicates')
    op.drop_index(op.f('idx_duplicates_original'), table_name='duplicates')
    op.create_unique_constraint('uq_duplicate_pair', 'duplicates', ['original_id', 'duplicate_id'])
    op.add_column('listings', sa.Column('landmark', sa.String(length=255), nullable=True))
    op.add_column('listings', sa.Column('min_period_months', sa.SmallInteger(), nullable=True))
    op.add_column('listings', sa.Column('utilities_included', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('no_deposit', sa.Boolean(), nullable=False))
    op.add_column('listings', sa.Column('condition', sa.String(length=100), nullable=True))
    op.add_column('listings', sa.Column('house_type', sa.String(length=100), nullable=True))
    op.add_column('listings', sa.Column('has_washing_machine', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('has_refrigerator', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('has_balcony', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('pets_allowed', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('kids_allowed', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('description_clean', sa.Text(), nullable=True))
    op.alter_column('listings', 'is_real_estate',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('listings', 'has_commission',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('listings', 'parse_score',
               existing_type=sa.SMALLINT(),
               server_default=None,
               nullable=False)
    op.alter_column('listings', 'needs_review',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_listings_deal_type'), table_name='listings')
    op.drop_index(op.f('idx_listings_district'), table_name='listings')
    op.drop_index(op.f('idx_listings_filter'), table_name='listings', postgresql_where='(is_real_estate = true)')
    op.drop_index(op.f('idx_listings_location'), table_name='listings')
    op.drop_index(op.f('idx_listings_object_type'), table_name='listings')
    op.drop_index(op.f('idx_listings_price'), table_name='listings')
    op.drop_index(op.f('idx_listings_rooms'), table_name='listings')
    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_media_phash'), table_name='media')
    op.drop_index(op.f('idx_media_post'), table_name='media')
    op.drop_index(op.f('idx_media_type'), table_name='media')
    op.drop_constraint(op.f('media_post_id_message_id_key'), 'media', type_='unique')
    op.create_unique_constraint('uq_media_post_message', 'media', ['post_id', 'message_id'])
    op.alter_column('posts', 'text_len',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('posts', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('posts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_posts_channel'), table_name='posts')
    op.drop_index(op.f('idx_posts_hashtags'), table_name='posts', postgresql_using='gin')
    op.drop_index(op.f('idx_posts_not_deleted'), table_name='posts', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_posts_phones'), table_name='posts', postgresql_using='gin')
    op.drop_index(op.f('idx_posts_published'), table_name='posts')
    op.drop_index(op.f('idx_posts_text_search'), table_name='posts', postgresql_using='gin')
    op.drop_constraint(op.f('posts_channel_id_message_id_key'), 'posts', type_='unique')
    op.create_unique_constraint('uq_post_channel_message', 'posts', ['channel_id', 'message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_post_channel_message', 'posts', type_='unique')
    op.create_unique_constraint(op.f('posts_channel_id_message_id_key'), 'posts', ['channel_id', 'message_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_posts_text_search'), 'posts', [sa.literal_column("to_tsvector('russian'::regconfig, text_raw)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_posts_published'), 'posts', [sa.literal_column('published_at DESC')], unique=False)
    op.create_index(op.f('idx_posts_phones'), 'posts', ['phones'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_posts_not_deleted'), 'posts', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_posts_hashtags'), 'posts', ['hashtags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_posts_channel'), 'posts', ['channel_id'], unique=False)
    op.alter_column('posts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('posts', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('posts', 'text_len',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.drop_constraint('uq_media_post_message', 'media', type_='unique')
    op.create_unique_constraint(op.f('media_post_id_message_id_key'), 'media', ['post_id', 'message_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('idx_media_post'), 'media', ['post_id'], unique=False)
    op.create_index(op.f('idx_media_phash'), 'media', ['phash'], unique=False)
    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.create_index(op.f('idx_listings_rooms'), 'listings', ['rooms'], unique=False)
    op.create_index(op.f('idx_listings_price'), 'listings', ['price', 'currency'], unique=False)
    op.create_index(op.f('idx_listings_object_type'), 'listings', ['object_type'], unique=False)
    op.create_index(op.f('idx_listings_location'), 'listings', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('idx_listings_filter'), 'listings', ['deal_type', 'object_type', 'rooms', 'price'], unique=False, postgresql_where='(is_real_estate = true)')
    op.create_index(op.f('idx_listings_district'), 'listings', ['district_id'], unique=False)
    op.create_index(op.f('idx_listings_deal_type'), 'listings', ['deal_type'], unique=False)
    op.alter_column('listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('listings', 'needs_review',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('listings', 'parse_score',
               existing_type=sa.SMALLINT(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('listings', 'has_commission',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('listings', 'is_real_estate',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.drop_column('listings', 'description_clean')
    op.drop_column('listings', 'kids_allowed')
    op.drop_column('listings', 'pets_allowed')
    op.drop_column('listings', 'has_balcony')
    op.drop_column('listings', 'has_refrigerator')
    op.drop_column('listings', 'has_washing_machine')
    op.drop_column('listings', 'house_type')
    op.drop_column('listings', 'condition')
    op.drop_column('listings', 'no_deposit')
    op.drop_column('listings', 'utilities_included')
    op.drop_column('listings', 'min_period_months')
    op.drop_column('listings', 'landmark')
    op.drop_constraint('uq_duplicate_pair', 'duplicates', type_='unique')
    op.create_index(op.f('idx_duplicates_original'), 'duplicates', ['original_id'], unique=False)
    op.create_index(op.f('idx_duplicates_duplicate'), 'duplicates', ['duplicate_id'], unique=False)
    op.create_unique_constraint(op.f('duplicates_original_id_duplicate_id_key'), 'duplicates', ['original_id', 'duplicate_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('duplicates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('districts', 'city',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Ташкент'::character varying"),
               nullable=True)
    op.create_index(op.f('idx_deletion_log_detected'), 'deletion_log', [sa.literal_column('detected_at DESC')], unique=False)
    op.alter_column('deletion_log', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.create_index(op.f('idx_channels_telegram_id'), 'channels', ['telegram_id'], unique=False)
    op.create_index(op.f('idx_channels_active'), 'channels', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('channels', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('channels', 'chat_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'channel'::character varying"),
               nullable=True)
    # ### end Alembic commands ###
